services:
  
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data
  
  server:
    image: todo-back-dev
    build:
      context: ./todo-backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    environment:
      - PORT=5000
      - REDIS_URL=redis://redis:6379/
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: todo-back-dev
    depends_on:
      - mongo
      - redis
    
  app:
    image: todo-front-dev
    build:
      context: ./todo-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend/:/usr/src/app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000/api/
    container_name: todo-front-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server